//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class TiendaEnLineaEntities : DbContext
{
    public TiendaEnLineaEntities()
        : base("name=TiendaEnLineaEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<products> products { get; set; }
    public virtual DbSet<sessions> sessions { get; set; }
    public virtual DbSet<users> users { get; set; }
    public virtual DbSet<warehouse> warehouse { get; set; }
    public virtual DbSet<warehouse_products> warehouse_products { get; set; }
}
